CREATE TABLE roles
(
    id         BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'PK',

    name       VARCHAR(50)  NOT NULL COMMENT '역할 이름 (ROLE_USER/ROLE_ADMIN/ROLE_SUPER_ADMIN)',

    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 시각',
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 시각',


    PRIMARY KEY (id),
    UNIQUE KEY uk_roles_name (name)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
  COMMENT = '역할 (권한 그룹)';
